Fix build with Gerrit 2.12
compile error, cannot find symbol: method get()

ChangeUpdatedListener.java:106
location: variable change of type com.google.gerrit.server.data.ChangeAttribute

ChangeUpdatedListener.java:107
location: variable patchSet of type com.google.gerrit.server.data.PatchSetAttribute

ChangeUpdatedListener.java:121
location: variable patchSet of type com.google.gerrit.server.data.PatchSetAttribute

Change-Id: Ib6132fbf6a9edec8bcdcd93040e03f0d90ffdfe8